version: '2'
services: 
    web:
        build: web
        ports: 
            - "5000:5000"
        env_file: .env_file
        depends_on: 
            - redis
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"