version: '2'
services: 
    web:
        build: 
            context: .
            dockerfile: web/Dockerfile
        ports: 
            - "5000:5000"
        env_file: .env
        volumes:
            - ./web:/app