version: '2'
services: 
    web:
        build: web
        ports: 
            - "5000:5000"
        env_file: .env
        volumes:
            - ./web:/app
        depends_on: 
            - redis
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        expose:
            - "6379"
        entrypoint: redis-server --appendonly yes